#ifndef PINS_H
#define PINS_H

// Boron Pins
#define IO_INT_PIN D2
#define IO_2_INT_PIN D3
#define I2C_RESET_PIN D4
#define TRANSFER_BLUE_RESERVED_PIN D5
#define TRANSFER_RED_RESERVED_PIN D6
#define AUX_PWM_PIN D7
#define HORN_EN_PIN D8

#define PAIL_SENSOR_PIN A0
#define PRESSURE_RED_PIN A1
#define PRESSURE_BLUE_PIN A2
#define AMBIENT_TEMPERATURE_PIN A3
#define MIKROBUS_1_PWM_PIN A4
#define MIKROBUS_2_PWM_PIN A5

// I/O Expander 1 Pins
#define IO1_MIKROBUS_2_CS GPA0
#define IO1_MIKROBUS_2_RST GPA1
#define IO1_MIKROBUS_2_INT GPA2

#define IO1_SD_CS GPB0
#define IO1_SD_DET GPB1
#define IO1_USER_REMOTE GPB2
#define IO1_RADIO_INT GPB3
#define IO1_RADIO_CS GPB4
#define IO1_MIKROBUS_1_RST GPB5
#define IO1_MIKROBUS_1_CS GPB6
#define IO1_MIKROBUS_1_INT GPB7

// I/O Expander 2 Pins
#define IO2_AIR_RED_EN GPA1
#define IO2_AIR_BLUE_EN GPA2
#define IO2_VALVE_1_EN GPA3
#define IO2_VALVE_2_EN GPA4
#define IO2_VALVE_3_EN GPA5
#define IO2_ADC_1_RDY GPA6
#define IO2_ADC_2_RDY GPA7

#define IO2_TRANSFER_BLUE_EN GPB0
#define IO2_TRANSFER_RED_EN GPB1
#define IO2_LIQUID_SENSOR_RED GPB2
#define IO2_LIQUID_SENSOR_BLUE GPB3
#define IO2_AUX_CS GPB4
#define IO2_AUX_RST GPB5
#define IO2_AUX_INT GPB6


// Analog Expander 1 Pins
#define MIKROBUS_1_AN AIN0
#define MIKROBUS_2_AN AIN1
#define AUX_AN AIN2
#define PAIL_SENSOR_DUPLICATE AIN3


#endif
